/* ═══════════════════════════════════════════════
   EXPANDED TRADING PATTERNS DATA
   ═══════════════════════════════════════════════ */

export interface TradingPattern {
  id: number
  name: string
  type: 'Reversal' | 'Continuation' | 'Bilateral'
  bias: 'Bullish' | 'Bearish' | 'Neutral'
  reliability: 'High' | 'Medium' | 'Low'
  successRate: number
  description: string
  howToTrade: string
  stopLoss: string
  target: string
  psychology: string
  svgType: string
}

export const TRADING_PATTERNS: TradingPattern[] = [
  // ═══════════════════════════════════════════
  // REVERSAL PATTERNS — Price Action / Chart
  // ═══════════════════════════════════════════
  { id: 1, name: 'Head & Shoulders', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 82,
    description: 'Three peaks \u2014 middle (head) is highest, two outer (shoulders) are lower and roughly equal. Neckline connects the two troughs. One of the most reliable reversal patterns in technical analysis.',
    howToTrade: 'Enter short when price breaks below neckline. Volume should decline on the right shoulder.',
    stopLoss: 'Above the right shoulder peak',
    target: 'Head-to-neckline distance projected downward',
    psychology: 'Buyers exhaust trying to push higher high. Right shoulder failure signals dominance shift to sellers.',
    svgType: 'headShoulders' },

  { id: 2, name: 'Inverse Head & Shoulders', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 83,
    description: 'Mirror of H&S \u2014 three troughs with the middle (head) being the lowest. Breakout above the neckline signals a strong trend reversal from bearish to bullish.',
    howToTrade: 'Enter long on breakout above neckline with volume confirmation.',
    stopLoss: 'Below the right shoulder trough',
    target: 'Head-to-neckline distance projected upward',
    psychology: 'Sellers exhaust; right trough fails to make lower low. Buyers step in aggressively.',
    svgType: 'headShoulders' },

  { id: 3, name: 'Double Top', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 79,
    description: 'Two peaks at nearly the same price level (M-shape). The pattern completes when price breaks below the support level (valley between peaks).',
    howToTrade: 'Enter short on confirmed break below the neckline. Wait for volume spike.',
    stopLoss: 'Above the second peak',
    target: 'Peak-to-neckline height projected downward',
    psychology: 'Price fails to break above resistance twice. The failure convinces bulls to exit.',
    svgType: 'doubleTop' },

  { id: 4, name: 'Double Bottom', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 80,
    description: 'Two troughs at similar lows (W-shape). Breakout above the resistance level confirms trend reversal from bearish to bullish.',
    howToTrade: 'Enter long on breakout above the neckline with rising volume.',
    stopLoss: 'Below the second trough',
    target: 'Trough-to-neckline height projected upward',
    psychology: 'Sellers fail to push price lower twice. Bears lose conviction, bulls enter.',
    svgType: 'doubleBottom' },

  { id: 5, name: 'Triple Top', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 85,
    description: 'Three attempts at the same resistance level, all failing. More reliable than double top as it shows stronger resistance.',
    howToTrade: 'Short on confirmed break below support. Volume confirmation critical.',
    stopLoss: 'Above the third peak',
    target: 'Peak-to-support distance projected downward',
    psychology: 'Three failures = strong resistance. Bulls give up after the third attempt.',
    svgType: 'tripleTop' },

  { id: 6, name: 'Triple Bottom', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 86,
    description: 'Three troughs at similar lows. The most reliable bottoming pattern. Breakout above resistance signals strong bullish reversal.',
    howToTrade: 'Go long on breakout above resistance with strong volume.',
    stopLoss: 'Below the third trough',
    target: 'Trough-to-resistance distance projected upward',
    psychology: 'Bears exhaust after three failed breakout attempts. Institutional buying often visible.',
    svgType: 'tripleBottom' },

  { id: 7, name: 'Rounding Bottom (Cup)', type: 'Reversal', bias: 'Bullish', reliability: 'Medium', successRate: 72,
    description: 'Gradual, rounded transition from downtrend to uptrend resembling a "U" shape. Volume often mirrors the shape (low in middle, higher at breakout).',
    howToTrade: 'Enter long as price breaks above the rim level. Use volume to confirm.',
    stopLoss: 'Below the lowest point of the rounding bottom',
    target: 'Depth of the cup projected upward',
    psychology: 'Slow shift from bearish to bullish sentiment. Institutional accumulation phase.',
    svgType: 'roundingBottom' },

  { id: 8, name: 'Rounding Top', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 70,
    description: 'Inverted U-shape. Gradual transition from uptrend to downtrend. Volume is usually higher at the start and end, lower in the middle.',
    howToTrade: 'Short on confirmed break below the rounding support level.',
    stopLoss: 'Above the highest point of the rounding top',
    target: 'Depth of the rounding projected downward',
    psychology: 'Buyers gradually lose conviction. Sellers slowly take control.',
    svgType: 'roundingBottom' },

  { id: 9, name: 'Diamond Top', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 71,
    description: 'Price first creates expanding triangle then contracting triangle. Signals exhaustion at the top of an uptrend.',
    howToTrade: 'Short on break below the lower support of the diamond.',
    stopLoss: 'Above the diamond\u2019s highest point',
    target: 'Diamond height projected downward',
    psychology: 'Increasing volatility followed by compression = indecision resolving downward.',
    svgType: 'descendingTriangle' },

  { id: 10, name: 'Diamond Bottom', type: 'Reversal', bias: 'Bullish', reliability: 'Medium', successRate: 72,
    description: 'Mirror of diamond top. Expanding then contracting triangle at a bottom. Signals bullish reversal.',
    howToTrade: 'Long on break above the upper resistance of the diamond.',
    stopLoss: 'Below the diamond\u2019s lowest point',
    target: 'Diamond height projected upward',
    psychology: 'Volatility expansion shows panic, then compression shows accumulation.',
    svgType: 'ascendingTriangle' },

  { id: 11, name: 'Broadening Top', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 68,
    description: 'Five minor reversals with expanding price range. Each swing makes a higher high and lower low. Shows extreme indecision and volatility.',
    howToTrade: 'Short on break below the fifth reversal\u2019s low.',
    stopLoss: 'Above the highest broadening high',
    target: 'Pattern height projected downward',
    psychology: 'Market is losing control. Wide swings show panic and euphoria alternating rapidly.',
    svgType: 'headShoulders' },

  { id: 12, name: 'Broadening Bottom', type: 'Reversal', bias: 'Bullish', reliability: 'Medium', successRate: 69,
    description: 'Mirror of broadening top. Five reversals with expanding range at a bottom.',
    howToTrade: 'Long on break above the fifth reversal\u2019s high.',
    stopLoss: 'Below the lowest broadening low',
    target: 'Pattern height projected upward',
    psychology: 'Panic selling gives way to aggressive buying. Volatility resolves bullishly.',
    svgType: 'doubleBottom' },

  { id: 13, name: 'Bump and Run Reversal', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 76,
    description: 'Rapid acceleration (bump) after a steady uptrend, followed by a sharp reversal. The bump is the final exhaustion move.',
    howToTrade: 'Short when price breaks below the trendline that connected the pre-bump advance.',
    stopLoss: 'Above the bump peak',
    target: 'Bump height projected downward from the trendline break',
    psychology: 'Euphoric buying creates an unsustainable spike. When it reverses, it reverses hard.',
    svgType: 'doubleTop' },

  { id: 14, name: 'Bump and Run (Bullish)', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 75,
    description: 'Mirror of bearish bump and run. Rapid acceleration downward followed by sharp reversal upward.',
    howToTrade: 'Long when price breaks above the downtrend line connecting the pre-bump decline.',
    stopLoss: 'Below the bump trough',
    target: 'Bump depth projected upward',
    psychology: 'Panic selling creates an unsustainable spike down. Shorts cover and buyers rush in.',
    svgType: 'doubleBottom' },

  { id: 15, name: 'Island Reversal', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 81,
    description: 'Price gaps up, trades in a range for a few days, then gaps down \u2014 leaving an "island" of prices disconnected from the main trend.',
    howToTrade: 'Short on the gap-down day. The island high is strong resistance.',
    stopLoss: 'Above the island high',
    target: 'Distance from island to prior trend projected downward',
    psychology: 'Buyers got trapped on the island. When price gaps down, they panic sell.',
    svgType: 'doubleTop' },

  { id: 16, name: 'Island Reversal (Bullish)', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 82,
    description: 'Price gaps down, trades in a range, then gaps up \u2014 leaving an island. Very strong reversal signal.',
    howToTrade: 'Long on the gap-up day. The island low is strong support.',
    stopLoss: 'Below the island low',
    target: 'Distance from island to prior trend projected upward',
    psychology: 'Sellers got trapped. Short covering plus new buying creates explosive moves.',
    svgType: 'doubleBottom' },

  { id: 17, name: 'Key Reversal Bar', type: 'Reversal', bias: 'Neutral', reliability: 'Medium', successRate: 66,
    description: 'A single bar that makes a new high (or low) but closes in the opposite direction. Shows strong rejection of the new extreme.',
    howToTrade: 'Trade in the direction of the close. Enter on the next bar.',
    stopLoss: 'Beyond the key reversal bar\u2019s extreme',
    target: 'Nearest support or resistance',
    psychology: 'Price pushed to a new extreme but got rejected. The close tells the real story.',
    svgType: 'hammer' },

  { id: 18, name: 'Falling Wedge', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 77,
    description: 'Both support and resistance slope downward but converge. Price compresses into a smaller range. Usually breaks upward.',
    howToTrade: 'Long on breakout above the upper trendline with volume.',
    stopLoss: 'Below the lower trendline',
    target: 'Widest part of the wedge added to breakout point',
    psychology: 'Sellers are losing momentum. Each push lower is weaker. Buyers are waiting.',
    svgType: 'symmetricalTriangle' },

  { id: 19, name: 'Rising Wedge', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 76,
    description: 'Both support and resistance slope upward but converge. Each rally is weaker. Usually breaks downward.',
    howToTrade: 'Short on breakdown below the lower trendline.',
    stopLoss: 'Above the upper trendline',
    target: 'Widest part of the wedge subtracted from breakdown point',
    psychology: 'Buyers are losing momentum. Each push higher is weaker. Sellers are waiting.',
    svgType: 'symmetricalTriangle' },

  { id: 20, name: 'Ascending Wedge (Bullish Continuation)', type: 'Continuation', bias: 'Bullish', reliability: 'Medium', successRate: 65,
    description: 'In an uptrend, a rising wedge can act as a continuation pattern. The converging trendlines show consolidation before the next leg up.',
    howToTrade: 'Long on breakout above the upper trendline in an established uptrend.',
    stopLoss: 'Below the wedge low',
    target: 'Prior trend height added to breakout',
    psychology: 'Bulls are consolidating before the next push. The wedge is a pause, not exhaustion.',
    svgType: 'ascendingTriangle' },

  // ═══════════════════════════════════════════
  // REVERSAL PATTERNS — Candlestick
  // ═══════════════════════════════════════════
  { id: 21, name: 'Hammer', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 78,
    description: 'Single candlestick with small body at top and long lower wick (2x+ body). Appears after a downtrend. Shows rejected lower prices.',
    howToTrade: 'Long on next candle opening above hammer\u2019s body. Confirm with volume.',
    stopLoss: 'Below the hammer\u2019s lowest point',
    target: 'Recent resistance level',
    psychology: 'Sellers tried pushing price down but buyers stepped in aggressively. Bullish rejection.',
    svgType: 'hammer' },

  { id: 22, name: 'Inverted Hammer', type: 'Reversal', bias: 'Bullish', reliability: 'Medium', successRate: 67,
    description: 'Small body at bottom, long upper wick. Appears after a downtrend. Shows initial buying pressure that got rejected but signals potential reversal.',
    howToTrade: 'Long on confirmation candle closing above the inverted hammer\u2019s high.',
    stopLoss: 'Below the inverted hammer\u2019s low',
    target: 'Recent resistance level',
    psychology: 'Buyers tried to push price up. Even though it got rejected, it shows buying interest.',
    svgType: 'shootingStar' },

  { id: 23, name: 'Hanging Man', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 64,
    description: 'Same shape as hammer but appears after an UPTREND. The long lower wick shows selling pressure emerging at highs.',
    howToTrade: 'Short on confirmation candle closing below the hanging man\u2019s body.',
    stopLoss: 'Above the hanging man\u2019s high',
    target: 'Recent support level',
    psychology: 'Same shape as hammer but context matters. At the top, the lower wick shows bears emerging.',
    svgType: 'hammer' },

  { id: 24, name: 'Shooting Star', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 77,
    description: 'Mirror of hammer \u2014 small body at bottom, long upper wick. Appears after uptrend. Shows rejected higher prices.',
    howToTrade: 'Short on next candle opening below the star\u2019s body.',
    stopLoss: 'Above the shooting star\u2019s highest point',
    target: 'Recent support level',
    psychology: 'Buyers attempted breakout but sellers hammered it back down. Bearish rejection.',
    svgType: 'shootingStar' },

  { id: 25, name: 'Doji', type: 'Reversal', bias: 'Neutral', reliability: 'Medium', successRate: 65,
    description: 'Opening and closing prices are virtually equal. Cross or plus shape. Indicates market indecision \u2014 potential reversal when appearing at extremes.',
    howToTrade: 'Wait for confirmation candle. Trade in direction of breakout from the doji range.',
    stopLoss: 'Beyond the doji\u2019s high or low',
    target: 'Nearest support/resistance',
    psychology: 'Buyers and sellers are perfectly balanced. The next move reveals who won.',
    svgType: 'doji' },

  { id: 26, name: 'Dragonfly Doji', type: 'Reversal', bias: 'Bullish', reliability: 'Medium', successRate: 70,
    description: 'Doji with a long lower wick and no upper wick. Looks like a "T". Shows strong rejection of lower prices.',
    howToTrade: 'Long on confirmation candle closing above the dragonfly doji\u2019s high.',
    stopLoss: 'Below the dragonfly doji\u2019s low',
    target: 'Recent resistance',
    psychology: 'Sellers pushed price way down but buyers recovered everything. Very bullish.',
    svgType: 'hammer' },

  { id: 27, name: 'Gravestone Doji', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 69,
    description: 'Doji with a long upper wick and no lower wick. Looks like an inverted "T". Shows strong rejection of higher prices.',
    howToTrade: 'Short on confirmation candle closing below the gravestone doji\u2019s low.',
    stopLoss: 'Above the gravestone doji\u2019s high',
    target: 'Recent support',
    psychology: 'Buyers pushed price way up but sellers recovered everything. Very bearish.',
    svgType: 'shootingStar' },

  { id: 28, name: 'Bullish Engulfing', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 80,
    description: 'Two candles. Second (green) candle completely engulfs the first (red) candle. Strong reversal signal after downtrend.',
    howToTrade: 'Long on opening of the third candle. Higher volume on engulfing candle = stronger signal.',
    stopLoss: 'Below the engulfing candle\u2019s low',
    target: 'Previous swing high',
    psychology: 'Sudden shift from selling to aggressive buying. Bears get trapped.',
    svgType: 'engulfing' },

  { id: 29, name: 'Bearish Engulfing', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 79,
    description: 'Inverse of bullish engulfing. Large red candle fully engulfs prior green candle. Strong bearish reversal after uptrend.',
    howToTrade: 'Short on opening of the third candle. Volume confirmation important.',
    stopLoss: 'Above the engulfing candle\u2019s high',
    target: 'Previous swing low',
    psychology: 'Aggressive selling overwhelms buyers. Bulls get trapped in losing positions.',
    svgType: 'engulfing' },

  { id: 30, name: 'Morning Star', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 84,
    description: 'Three-candle pattern: bearish candle \u2192 small-bodied candle (gap) \u2192 bullish candle. Signals powerful bottom reversal.',
    howToTrade: 'Long when third candle closes above midpoint of first candle.',
    stopLoss: 'Below the second candle\u2019s low',
    target: 'Previous resistance level',
    psychology: 'Selling exhaustion \u2192 indecision \u2192 strong buying. Classic three-phase reversal.',
    svgType: 'morningStar' },

  { id: 31, name: 'Evening Star', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 83,
    description: 'Mirror of morning star. Three candles: bullish \u2192 small body \u2192 bearish. Top reversal pattern.',
    howToTrade: 'Short when third candle closes below midpoint of first candle.',
    stopLoss: 'Above the second candle\u2019s high',
    target: 'Previous support level',
    psychology: 'Buying exhaustion \u2192 indecision \u2192 aggressive selling. Institutional distribution.',
    svgType: 'eveningStar' },

  { id: 32, name: 'Morning Doji Star', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 86,
    description: 'Like morning star but the middle candle is a doji. Even stronger indecision signal. Very reliable.',
    howToTrade: 'Long when third candle closes above midpoint of first candle.',
    stopLoss: 'Below the doji\u2019s low',
    target: 'Previous resistance',
    psychology: 'The doji shows even more indecision than a small body. The reversal is more powerful.',
    svgType: 'morningStar' },

  { id: 33, name: 'Evening Doji Star', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 85,
    description: 'Like evening star but middle candle is a doji. Very strong bearish reversal.',
    howToTrade: 'Short when third candle closes below midpoint of first candle.',
    stopLoss: 'Above the doji\u2019s high',
    target: 'Previous support',
    psychology: 'Doji at the top shows extreme indecision before the reversal.',
    svgType: 'eveningStar' },

  { id: 34, name: 'Three White Soldiers', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 81,
    description: 'Three consecutive bullish candles with higher opens and higher closes. Each candle opens within the previous body.',
    howToTrade: 'Long on the fourth candle. Best after a downtrend or at support.',
    stopLoss: 'Below the first candle\u2019s open',
    target: 'Previous swing high or resistance',
    psychology: 'Sustained buying pressure. Each day bulls open higher and close higher.',
    svgType: 'threeWhiteSoldiers' },

  { id: 35, name: 'Three Black Crows', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 80,
    description: 'Three consecutive bearish candles with lower opens and lower closes. Strong bearish reversal after uptrend.',
    howToTrade: 'Short on the fourth candle. Confirm with volume.',
    stopLoss: 'Above the first candle\u2019s open',
    target: 'Previous swing low or support',
    psychology: 'Sustained selling pressure. Bears in complete control for three sessions.',
    svgType: 'threeBlackCrows' },

  { id: 36, name: 'Bullish Harami', type: 'Reversal', bias: 'Bullish', reliability: 'Medium', successRate: 68,
    description: 'Small green candle completely inside the previous large red candle. "Pregnant" pattern. Signals potential bottom.',
    howToTrade: 'Long on confirmation candle closing above the harami candle.',
    stopLoss: 'Below the harami candle\u2019s low',
    target: 'Previous swing high',
    psychology: 'Selling pressure is weakening. The small candle shows bears losing momentum.',
    svgType: 'bullishHarami' },

  { id: 37, name: 'Bearish Harami', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 67,
    description: 'Small red candle inside previous large green candle. Signals potential top.',
    howToTrade: 'Short on confirmation candle closing below the harami candle.',
    stopLoss: 'Above the harami candle\u2019s high',
    target: 'Previous swing low',
    psychology: 'Buying momentum is fading. Bulls can\u2019t push price higher.',
    svgType: 'bearishHarami' },

  { id: 38, name: 'Piercing Pattern', type: 'Reversal', bias: 'Bullish', reliability: 'Medium', successRate: 70,
    description: 'Two candles: red candle followed by green candle that opens below prior low and closes above midpoint of prior body.',
    howToTrade: 'Long on confirmation. Stronger when it occurs at oversold levels.',
    stopLoss: 'Below the green candle\u2019s low',
    target: 'Previous resistance',
    psychology: 'Buyers aggressively step in after gap down. Bears get nervous.',
    svgType: 'piercing' },

  { id: 39, name: 'Dark Cloud Cover', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 69,
    description: 'Green candle followed by red candle that opens above prior high and closes below midpoint of prior body.',
    howToTrade: 'Short on confirmation. Stronger at overbought levels.',
    stopLoss: 'Above the red candle\u2019s high',
    target: 'Previous support',
    psychology: 'Sellers aggressively enter after gap up. Bulls get nervous.',
    svgType: 'darkCloud' },

  { id: 40, name: 'Tweezer Top', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 72,
    description: 'Two candles with identical (or nearly identical) highs. First is bullish, second is bearish. Shows strong rejection at a level.',
    howToTrade: 'Short on confirmation candle. The tweezer high acts as strong resistance.',
    stopLoss: 'Above the tweezer high',
    target: 'Previous swing low',
    psychology: 'Price tested the same level twice and got rejected. Bears defend that level.',
    svgType: 'tweezerTop' },

  { id: 41, name: 'Tweezer Bottom', type: 'Reversal', bias: 'Bullish', reliability: 'Medium', successRate: 73,
    description: 'Two candles with identical lows. First is bearish, second is bullish. Shows strong support at a level.',
    howToTrade: 'Long on confirmation candle. The tweezer low acts as strong support.',
    stopLoss: 'Below the tweezer low',
    target: 'Previous swing high',
    psychology: 'Price tested the same support twice. Bulls defend that level successfully.',
    svgType: 'tweezerBottom' },

  { id: 42, name: 'Abandoned Baby (Bullish)', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 87,
    description: 'Three candles: bearish \u2192 doji (gapped down) \u2192 bullish (gapped up). The doji is "abandoned" by the gaps. Extremely rare but very reliable.',
    howToTrade: 'Long on the third candle. One of the most reliable reversal patterns.',
    stopLoss: 'Below the doji\u2019s low',
    target: 'Previous resistance',
    psychology: 'Total exhaustion of sellers followed by explosive buying. The gaps show conviction.',
    svgType: 'morningStar' },

  { id: 43, name: 'Abandoned Baby (Bearish)', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 86,
    description: 'Three candles: bullish \u2192 doji (gapped up) \u2192 bearish (gapped down).',
    howToTrade: 'Short on the third candle.',
    stopLoss: 'Above the doji\u2019s high',
    target: 'Previous support',
    psychology: 'Total exhaustion of buyers followed by explosive selling.',
    svgType: 'eveningStar' },

  { id: 44, name: 'Three Inside Up', type: 'Reversal', bias: 'Bullish', reliability: 'High', successRate: 82,
    description: 'Bullish harami followed by a confirmation candle that closes above the first candle\u2019s open. Also called "confirmed harami".',
    howToTrade: 'Long on the third candle close above the first candle\u2019s open.',
    stopLoss: 'Below the second candle\u2019s low',
    target: 'Previous resistance',
    psychology: 'The confirmation candle proves the harami was real. Bears have given up.',
    svgType: 'bullishHarami' },

  { id: 45, name: 'Three Inside Down', type: 'Reversal', bias: 'Bearish', reliability: 'High', successRate: 81,
    description: 'Bearish harami followed by confirmation candle closing below the first candle\u2019s open.',
    howToTrade: 'Short on the third candle close below the first candle\u2019s open.',
    stopLoss: 'Above the second candle\u2019s high',
    target: 'Previous support',
    psychology: 'The confirmation candle proves the bearish harami was real. Bulls have given up.',
    svgType: 'bearishHarami' },

  { id: 46, name: 'Upside Gap Two Crows', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 66,
    description: 'Bullish candle \u2192 gap up \u2192 two bearish candles that fill the gap. Shows buyers losing control after a gap.',
    howToTrade: 'Short when the second crow closes below the first crow\u2019s close.',
    stopLoss: 'Above the second crow\u2019s high',
    target: 'Gap support level',
    psychology: 'The gap excited buyers but two bearish candles show sellers stepping in.',
    svgType: 'engulfing' },

  { id: 47, name: 'Advance Block', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 63,
    description: 'Three bullish candles with progressively smaller bodies and longer upper wicks. Shows weakening buying pressure.',
    howToTrade: 'Short on confirmation candle closing below the third candle\u2019s close.',
    stopLoss: 'Above the highest upper wick',
    target: 'Pattern\u2019s lowest point',
    psychology: 'Each bullish candle is weaker than the last. Buyers are tiring out.',
    svgType: 'threeWhiteSoldiers' },

  { id: 48, name: 'Deliberation Pattern', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 65,
    description: 'Two strong bullish candles followed by a small-bodied candle (or doji). Shows buyers pausing \u2014 potential exhaustion.',
    howToTrade: 'Short on confirmation candle closing below the third candle\u2019s close.',
    stopLoss: 'Above the highest high',
    target: 'Pattern\u2019s lowest point',
    psychology: 'After two strong bullish candles, the small candle shows buyers are uncertain.',
    svgType: 'morningStar' },

  { id: 49, name: 'Two Crows', type: 'Reversal', bias: 'Bearish', reliability: 'Medium', successRate: 64,
    description: 'Bullish candle \u2192 gap up \u2192 bearish candle that opens within the first body and closes below it.',
    howToTrade: 'Short on confirmation.',
    stopLoss: 'Above the second crow\u2019s high',
    target: 'Gap support',
    psychology: 'Gap up excited buyers but the bearish close shows sellers taking control.',
    svgType: 'engulfing' },

  { id: 50, name: 'Stick Sandwich', type: 'Reversal', bias: 'Bullish', reliability: 'Medium', successRate: 62,
    description: 'Red candle \u2192 green candle \u2192 red candle. Both red candles close at the same level. The green candle is "sandwiched".',
    howToTrade: 'Long on confirmation candle closing above the green candle\u2019s high.',
    stopLoss: 'Below the red candles\u2019 common close',
    target: 'Previous resistance',
    psychology: 'Sellers tried twice at the same level and failed. The sandwiched green candle shows buying.',
    svgType: 'engulfing' },

  // ═══════════════════════════════════════════
  // CONTINUATION PATTERNS
  // ═══════════════════════════════════════════
  { id: 51, name: 'Ascending Triangle', type: 'Continuation', bias: 'Bullish', reliability: 'High', successRate: 78,
    description: 'Flat upper resistance line with rising lower support line. Price compresses toward apex. Usually breaks upward.',
    howToTrade: 'Long on breakout above the flat resistance line with volume.',
    stopLoss: 'Below the rising support line',
    target: 'Triangle height added to breakout point',
    psychology: 'Buyers are progressively more aggressive (higher lows). Resistance eventually gives.',
    svgType: 'ascendingTriangle' },

  { id: 52, name: 'Descending Triangle', type: 'Continuation', bias: 'Bearish', reliability: 'High', successRate: 77,
    description: 'Flat lower support line with falling upper resistance line. Usually breaks downward.',
    howToTrade: 'Short on breakdown below the flat support line.',
    stopLoss: 'Above the falling resistance line',
    target: 'Triangle height subtracted from breakdown point',
    psychology: 'Sellers are progressively more aggressive (lower highs). Support eventually breaks.',
    svgType: 'descendingTriangle' },

  { id: 53, name: 'Symmetrical Triangle', type: 'Continuation', bias: 'Neutral', reliability: 'Medium', successRate: 68,
    description: 'Both support and resistance converge symmetrically. Breakout direction determines the trade.',
    howToTrade: 'Trade in the direction of the breakout. Wait for candle close beyond the triangle.',
    stopLoss: 'Beyond the opposite side of the triangle',
    target: 'Triangle height projected from breakout point',
    psychology: 'Market is consolidating. Both sides are equally strong until one gives.',
    svgType: 'symmetricalTriangle' },

  { id: 54, name: 'Bull Flag', type: 'Continuation', bias: 'Bullish', reliability: 'High', successRate: 82,
    description: 'Strong upward move (pole) followed by a slight downward channel (flag). One of the most reliable continuation patterns.',
    howToTrade: 'Long on breakout above the flag\u2019s upper boundary.',
    stopLoss: 'Below the flag\u2019s lower boundary',
    target: 'Pole height added to breakout point',
    psychology: 'Bulls taking a breather after a strong move. Bears can\u2019t push much lower.',
    svgType: 'flag' },

  { id: 55, name: 'Bear Flag', type: 'Continuation', bias: 'Bearish', reliability: 'High', successRate: 81,
    description: 'Strong downward move (pole) followed by a slight upward channel (flag).',
    howToTrade: 'Short on breakdown below the flag\u2019s lower boundary.',
    stopLoss: 'Above the flag\u2019s upper boundary',
    target: 'Pole height subtracted from breakdown point',
    psychology: 'Bears resting. Bulls can\u2019t push much higher. Selling resumes.',
    svgType: 'flag' },

  { id: 56, name: 'Pennant', type: 'Continuation', bias: 'Neutral', reliability: 'High', successRate: 79,
    description: 'Strong move (pole) followed by converging trendlines (small symmetrical triangle). Breakout usually continues the prior trend.',
    howToTrade: 'Trade in direction of breakout from the pennant.',
    stopLoss: 'Beyond the opposite side of the pennant',
    target: 'Pole height projected from breakout',
    psychology: 'Brief consolidation after a strong move. Energy builds for the next leg.',
    svgType: 'pennant' },

  { id: 57, name: 'Cup and Handle', type: 'Continuation', bias: 'Bullish', reliability: 'High', successRate: 83,
    description: 'Rounding bottom (cup) followed by a small downward drift (handle). Breakout above handle resistance signals continuation.',
    howToTrade: 'Long on breakout above the handle\u2019s resistance.',
    stopLoss: 'Below the handle\u2019s low',
    target: 'Cup depth added to breakout point',
    psychology: 'Institutional accumulation (cup) followed by a final shakeout (handle).',
    svgType: 'cupHandle' },

  { id: 58, name: 'Rectangle (Bullish)', type: 'Continuation', bias: 'Bullish', reliability: 'Medium', successRate: 71,
    description: 'Price bounces between parallel support and resistance lines. In an uptrend, usually breaks upward.',
    howToTrade: 'Long on breakout above the rectangle\u2019s resistance.',
    stopLoss: 'Below the rectangle\u2019s support',
    target: 'Rectangle height added to breakout',
    psychology: 'Consolidation in an uptrend. Buyers are accumulating before the next push.',
    svgType: 'ascendingTriangle' },

  { id: 59, name: 'Rectangle (Bearish)', type: 'Continuation', bias: 'Bearish', reliability: 'Medium', successRate: 70,
    description: 'Price bounces between parallel lines in a downtrend. Usually breaks downward.',
    howToTrade: 'Short on breakdown below the rectangle\u2019s support.',
    stopLoss: 'Above the rectangle\u2019s resistance',
    target: 'Rectangle height subtracted from breakdown',
    psychology: 'Consolidation in a downtrend. Sellers are distributing before the next drop.',
    svgType: 'descendingTriangle' },

  { id: 60, name: 'Measured Move (Bullish)', type: 'Continuation', bias: 'Bullish', reliability: 'Medium', successRate: 74,
    description: 'First leg up \u2192 consolidation \u2192 second leg up that is approximately the same size as the first leg.',
    howToTrade: 'Long during the consolidation, targeting the first leg\u2019s height from the consolidation.',
    stopLoss: 'Below the consolidation low',
    target: 'First leg height projected from consolidation breakout',
    psychology: 'The market moves in measured increments. The second leg often mirrors the first.',
    svgType: 'flag' },

  { id: 61, name: 'Measured Move (Bearish)', type: 'Continuation', bias: 'Bearish', reliability: 'Medium', successRate: 73,
    description: 'First leg down \u2192 consolidation \u2192 second leg down mirroring the first.',
    howToTrade: 'Short during the consolidation.',
    stopLoss: 'Above the consolidation high',
    target: 'First leg depth projected from consolidation breakdown',
    psychology: 'Selling pressure releases in waves. The second wave often matches the first.',
    svgType: 'flag' },

  { id: 62, name: 'Falling Wedge (Continuation)', type: 'Continuation', bias: 'Bullish', reliability: 'High', successRate: 75,
    description: 'In an uptrend, a falling wedge acts as a continuation pattern. The converging downward trendlines show a pause before the next leg up.',
    howToTrade: 'Long on breakout above the upper trendline.',
    stopLoss: 'Below the wedge low',
    target: 'Widest part added to breakout',
    psychology: 'Bulls are consolidating in a tight range. The breakout continues the trend.',
    svgType: 'symmetricalTriangle' },

  { id: 63, name: 'Rising Wedge (Continuation)', type: 'Continuation', bias: 'Bearish', reliability: 'High', successRate: 74,
    description: 'In a downtrend, a rising wedge acts as a continuation pattern. The converging upward trendlines show a pause before the next leg down.',
    howToTrade: 'Short on breakdown below the lower trendline.',
    stopLoss: 'Above the wedge high',
    target: 'Widest part subtracted from breakdown',
    psychology: 'Bears are consolidating. The breakdown continues the downtrend.',
    svgType: 'symmetricalTriangle' },

  { id: 64, name: 'Price Channel (Ascending)', type: 'Continuation', bias: 'Bullish', reliability: 'Medium', successRate: 72,
    description: 'Price moves between two parallel upward-sloping lines. Buy at the lower channel, sell at the upper channel.',
    howToTrade: 'Long at the lower channel line. Take profit at the upper channel line.',
    stopLoss: 'Below the lower channel line',
    target: 'Upper channel line',
    psychology: 'The market is in a steady uptrend. The channel defines the trading range.',
    svgType: 'ascendingTriangle' },

  { id: 65, name: 'Price Channel (Descending)', type: 'Continuation', bias: 'Bearish', reliability: 'Medium', successRate: 71,
    description: 'Price moves between two parallel downward-sloping lines.',
    howToTrade: 'Short at the upper channel line. Cover at the lower channel line.',
    stopLoss: 'Above the upper channel line',
    target: 'Lower channel line',
    psychology: 'The market is in a steady downtrend. The channel defines the trading range.',
    svgType: 'descendingTriangle' },

  { id: 66, name: 'Mat Hold (Bullish)', type: 'Continuation', bias: 'Bullish', reliability: 'High', successRate: 80,
    description: 'Five-candle pattern: bullish candle \u2192 three small bearish candles (all within first candle\u2019s range) \u2192 bullish candle that breaks above the first candle.',
    howToTrade: 'Long on the fifth candle when it breaks above the first candle\u2019s high.',
    stopLoss: 'Below the lowest of the three small candles',
    target: 'First candle\u2019s height projected upward',
    psychology: 'A brief pause in a strong uptrend. The three small candles show profit-taking, not reversal.',
    svgType: 'threeWhiteSoldiers' },

  { id: 67, name: 'Mat Hold (Bearish)', type: 'Continuation', bias: 'Bearish', reliability: 'High', successRate: 79,
    description: 'Five-candle pattern: bearish candle \u2192 three small bullish candles \u2192 bearish candle that breaks below the first candle.',
    howToTrade: 'Short on the fifth candle when it breaks below the first candle\u2019s low.',
    stopLoss: 'Above the highest of the three small candles',
    target: 'First candle\u2019s height projected downward',
    psychology: 'A brief pause in a strong downtrend. The three small candles show short-covering, not reversal.',
    svgType: 'threeBlackCrows' },

  // ═══════════════════════════════════════════
  // BILATERAL PATTERNS (Breakout Either Way)
  // ═══════════════════════════════════════════
  { id: 68, name: 'Symmetrical Triangle (Bilateral)', type: 'Bilateral', bias: 'Neutral', reliability: 'Medium', successRate: 68,
    description: 'Both trendlines converge symmetrically. Can break either way. Trade the breakout direction.',
    howToTrade: 'Place buy stop above upper trendline and sell stop below lower trendline. Cancel the other when one triggers.',
    stopLoss: 'Beyond the opposite trendline',
    target: 'Triangle height projected from breakout',
    psychology: 'Neither side has control. The breakout reveals who won the battle.',
    svgType: 'symmetricalTriangle' },

  { id: 69, name: 'Rectangle (Bilateral)', type: 'Bilateral', bias: 'Neutral', reliability: 'Medium', successRate: 65,
    description: 'Price oscillates between parallel support and resistance. Can break either way.',
    howToTrade: 'Place orders above resistance and below support. Trade the breakout.',
    stopLoss: 'Beyond the opposite side',
    target: 'Rectangle height projected from breakout',
    psychology: 'A tug-of-war. The breakout shows which side won.',
    svgType: 'ascendingTriangle' },

  { id: 70, name: 'Diamond (Bilateral)', type: 'Bilateral', bias: 'Neutral', reliability: 'Medium', successRate: 67,
    description: 'Expanding then contracting triangle. Can break either way. More common at tops but can appear anywhere.',
    howToTrade: 'Trade the breakout direction with volume confirmation.',
    stopLoss: 'Beyond the opposite side of the diamond',
    target: 'Diamond height projected from breakout',
    psychology: 'Volatility expansion followed by compression. The resolution can go either way.',
    svgType: 'symmetricalTriangle' },

  { id: 71, name: 'Megaphone Top', type: 'Bilateral', bias: 'Neutral', reliability: 'Low', successRate: 58,
    description: 'Expanding triangle with both trendlines diverging. Shows extreme volatility and indecision.',
    howToTrade: 'Trade breakouts in either direction. Use tight stops due to volatility.',
    stopLoss: 'Beyond the opposite trendline',
    target: 'Pattern height projected from breakout',
    psychology: 'Market is in chaos. Neither side can establish control. High-risk, high-reward.',
    svgType: 'headShoulders' },

  { id: 72, name: 'Contracting Triangle', type: 'Bilateral', bias: 'Neutral', reliability: 'Medium', successRate: 66,
    description: 'Like symmetrical triangle but the convergence is more extreme. The breakout is usually powerful.',
    howToTrade: 'Trade the breakout. The more extreme the convergence, the bigger the move.',
    stopLoss: 'Beyond the opposite side',
    target: 'Widest part projected from breakout',
    psychology: 'Extreme compression = extreme energy waiting to be released.',
    svgType: 'symmetricalTriangle' },
]
